import Mathlib

namespace Problem16

/--
A Galois extension such that the degree of the extension is a power of a prime \( p \) is
called a p-extension.
-/
class IsPExtension (F E : Type) [Field F] [Field E] [Algebra F E]
    (p : ℕ) : Prop extends IsGalois F E where
    rank_eq_pow : ∃ (n : ℕ), Module.rank F E = p ^ n

/--
Let $p$ be a prime and let $F$ be a field.
Let $K$ be a finite Galois extension of $F$ whose Galois group is a $p$-group (i.e., the degree
$[K : F]$ is a power of $p$). Such an extension is called a \emph{$p$-extension} (note that
$p$-extensions are Galois by definition). Let $L$ be a $p$-extension of $K$. Prove that the
Galois closure of $L$ over $F$ is a $p$-extension of $F$.
-/
theorem normalClosure_isPExtension_of_isPExtension (F E : Type) [Field F] [Field E]
    [Algebra F E] (L : IntermediateField F E) (K : IntermediateField F L) (p : ℕ) (hp : p.Prime)
    [IsPExtension F K p] [IsGalois K L] [IsPExtension K L p]
    (h_normalClosure : IsNormalClosure F L E) : IsPExtension F E p := by
  -- Step 1: Separability transports up the tower F ⊆ K ⊆ L
  haveI hsK : Algebra.IsSeparable F K := IsGalois.to_isSeparable
  haveI hsKL : Algebra.IsSeparable K L := IsGalois.to_isSeparable
  haveI hsL : Algebra.IsSeparable F L := Algebra.IsSeparable.trans F K L
  -- Step 2: E is separable over F. E is generated by roots of minpolys of elements of L over F
  -- (from the IsNormalClosure data), and those minpolys are separable since L/F is.
  haveI hsE : Algebra.IsSeparable F E := by
    rw [← separableClosure.eq_top_iff F E]
    have hsup : (⨆ x : L, IntermediateField.adjoin F ((minpoly F x).rootSet E)) =
        (⊤ : IntermediateField F E) :=
      h_normalClosure.adjoin_rootSet
    apply le_antisymm le_top
    rw [← hsup]
    refine iSup_le (α := IntermediateField F E) (fun x => ?_)
    rw [le_separableClosure_iff, IntermediateField.isSeparable_adjoin_iff_isSeparable]
    intro y hy
    have hxint : IsIntegral F x := Algebra.IsIntegral.isIntegral x
    have hmnz : minpoly F x ≠ 0 := minpoly.ne_zero hxint
    rw [Polynomial.mem_rootSet_of_ne hmnz] at hy
    have hxsep : (minpoly F x).Separable := Algebra.IsSeparable.isSeparable F x
    exact hxsep.of_dvd (minpoly.dvd F y hy)
  -- Step 3: E/F is Galois. Normality is from `IsNormalClosure.normal`.
  haveI hnE : Normal F E := h_normalClosure.normal
  haveI hgalE : IsGalois F E := { }
  -- Step 4: E/F is finite-dimensional. Move to AlgebraicClosure F where there is a canonical
  -- normal closure of L, which is finite-dimensional, and transport finiteness back via
  -- `IsNormalClosure.equiv`.
  haveI hfinK : FiniteDimensional F K := by
    obtain ⟨n, hn⟩ := IsPExtension.rank_eq_pow (F := F) (E := K) (p := p)
    exact Module.finite_of_rank_eq_nat (n := p ^ n) (by exact_mod_cast hn)
  haveI hfinKL : FiniteDimensional K L := by
    obtain ⟨n, hn⟩ := IsPExtension.rank_eq_pow (F := K) (E := L) (p := p)
    exact Module.finite_of_rank_eq_nat (n := p ^ n) (by exact_mod_cast hn)
  haveI hfinL : FiniteDimensional F L := FiniteDimensional.trans F K L
  haveI hfinE : FiniteDimensional F E := by
    let A := AlgebraicClosure F
    haveI : FiniteDimensional F (IntermediateField.normalClosure F L A) :=
      normalClosure.is_finiteDimensional F L A
    haveI hncA : IsNormalClosure F L (IntermediateField.normalClosure F L A) := by
      have hsplits : ∀ x : L, ((minpoly F x).map (algebraMap F A)).Splits :=
        fun _ => IsAlgClosed.splits_codomain _
      exact Algebra.IsAlgebraic.isNormalClosure_normalClosure hsplits
    let e : E ≃ₐ[F] (IntermediateField.normalClosure F L A : IntermediateField F A) :=
      IsNormalClosure.equiv (h := h_normalClosure) (h' := hncA)
    exact LinearEquiv.finiteDimensional e.symm.toLinearEquiv
  -- Step 5: rank E over F is a power of p.
  -- TODO: This is the genuinely hard part. Mathematical sketch:
  --   * E is generated over F by the F-algebra images σ(L) for σ : L →ₐ[F] E.
  --   * There are exactly [L:F] = p^(a+b) such embeddings (where [K:F]=p^a, [L:K]=p^b).
  --   * Each σ(L) has rank p^(a+b) over F (σ is injective).
  --   * The compositum E = ⨆ σ.fieldRange of finitely many extensions of p-power degree.
  --   * Using Galois correspondence: subgroups of Gal(E/F) of p-power index intersect to a
  --     subgroup of p-power index, since [G : H₁ ∩ H₂] | [G : H₁] · [G : H₂].
  --   * Equivalently, |Gal(E/F)| divides ∏ [σ.fieldRange : F]ᵒᵖ = p^something.
  refine { rank_eq_pow := ?_ }
  sorry

end Problem16
