import Mathlib

namespace Problem19

/--
Let $E$ denote the algebra $\mathbb{Q}(\sqrt{(2+\sqrt 2)(3+\sqrt 3)})
-/
abbrev E : Type := (Algebra.adjoin ℚ {Real.sqrt ((2 + Real.sqrt 2) * (3 + Real.sqrt 3))})

/-
Roadmap of the proof.

Write `α := √((2+√2)(3+√3)) ∈ ℝ`, `E := ℚ(α) ⊆ ℝ`, and
`F := ℚ(√2, √3) ⊆ ℝ`.  Throughout we work inside `ℝ`, so all square
roots refer to nonnegative real square roots.  The four square roots
that play the role of conjugates of `α` over `F` are
  `α := √((2+√2)(3+√3))`, `β := √((2-√2)(3+√3))`,
  `γ := √((2+√2)(3-√3))`, `δ := √((2-√2)(3-√3))`,
all positive real numbers.  We use repeatedly the algebraic identities
  `α·β = (3+√3)·√2`,   `α·γ = (2+√2)·√6`,   `α·δ = 2·√3`,
  `β·γ = ?`,           `β·δ = (2-√2)·√6`,   `γ·δ = (3-√3)·√2`,
each obtained from the formula
  `√(u·v) = √u · √v` (for `u, v ≥ 0`)
applied to suitable factorisations of the products `(2±√2)²(3±√3)²`,
`(4-2)(3±√3)²`, `(2±√2)²(9-3)`, etc.

Step 1 — Subfield `F = ℚ(√2, √3) ⊆ E` and `[F : ℚ] = 4`.
  By construction `α² = (2+√2)(3+√3) = 6 + 3√2 + 2√3 + √6 ∈ E`.  The
  four conjugates of `α²` under the Galois group of `ℚ(√2, √3)/ℚ` are
  the four products `u_{ε₁,ε₂} := (2 + ε₁√2)(3 + ε₂√3)` with
  `ε₁, ε₂ ∈ {±1}`; expanding shows they are pairwise distinct, so
  `α²` has degree exactly `4` over `ℚ`.  Hence
  `ℚ(α²) = ℚ(√2, √3) =: F`, and `[F : ℚ] = 4`.

Step 2 — `[E : ℚ] = 8`.
  The element `α ∈ ℝ_{≥ 0}` satisfies `α² = (2+√2)(3+√3) ∈ F`, so
  `[F(α) : F] ≤ 2`.  Equality `[F(α) : F] = 2` holds because
  `(2+√2)(3+√3)` is not a square in `F`: in any decomposition
  `(2+√2)(3+√3) = (p + q√2 + r√3 + s√6)²` with `p, q, r, s ∈ ℚ`, the
  coefficient of `√6` on the left is `1`, while on the right the
  coefficient of `√6` is `2(ps + qr)`; combining this with the equations
  for the other three coefficients of `1, √2, √3` yields no rational
  solution (a routine elimination on the four quadratic equations).
  Therefore `[E : F] = 2` and `[E : ℚ] = [E : F]·[F : ℚ] = 2·4 = 8`.

Step 3 — `E/ℚ` is Galois.
  Separability is automatic in characteristic zero, so it suffices to
  show that `E/ℚ` is normal, i.e.\ that all eight roots of the minimal
  polynomial of `α` lie in `E`.  Using the products listed above,
      `β = (3+√3)·√2 / α`,  `γ = (2+√2)·√6 / α`,  `δ = 2·√3 / α`,
  and `√2, √3, √6 ∈ F ⊆ E`, while `α ∈ E` is a unit (it is nonzero
  positive in `ℝ`, hence invertible in the field `E`).  Therefore
  `β, γ, δ ∈ E`, and the eight roots `±α, ±β, ±γ, ±δ` of the minimal
  polynomial of `α` all lie in `E`.  So `E/ℚ` is normal, hence Galois.

Step 4 — Two distinguished automorphisms `σ, τ` of order `4`.
  Since `E/ℚ` is Galois of degree `8`, the Galois group has order
  `8`.  The four roots of `min(α, F)` are `±α, ±β`, and there is a
  unique automorphism `σ ∈ Gal(E/ℚ)` characterised by
      `σ(√2) = -√2,  σ(√3) = √3,  σ(α) = β`.
  Computing `σ²(α) = σ(β) = σ((3+√3)·√2/α) =
  (3+√3)·(-√2)/β = -(3+√3)·√2/β = -α`,
  using `α·β = (3+√3)·√2` once more.  Hence `σ²(α) = -α`, so
  `σ⁴ = 1` and `σ² ≠ 1`, i.e.\ `σ` has order `4`.

  Similarly there is `τ ∈ Gal(E/ℚ)` with
      `τ(√2) = √2,  τ(√3) = -√3,  τ(α) = γ`,
  and the computation `τ²(α) = τ(γ) = (2+√2)·(-√6)/γ = -α` (using
  `τ(√6) = τ(√2)·τ(√3) = -√6`) shows `τ` has order `4`.  Note that
  `σ²(α) = -α = τ²(α)` and `σ²` and `τ²` both fix `F` pointwise, so
  they agree on the generator `α` of `E` over `F` and on `F` itself,
  whence `σ² = τ²`.

Step 5 — Quaternion relations.
  Using `α·β = (3+√3)·√2`, `α·γ = (2+√2)·√6`, `α·δ = 2·√3`,
  `β·δ = (2-√2)·√6`, `γ·δ = (3-√3)·√2`, one computes
      `σ(τ(α)) = σ(γ) = -(2-√2)·√6 / β = -δ`,
      `τ(σ(α)) = τ(β) = (3-√3)·√2 / γ = δ`.
  Thus `(σ·τ)(α) = -δ = -(τ·σ)(α)`.  Since both `σ·τ` and `τ·σ`
  preserve `F` (each restricts to the unique automorphism of `F`
  sending `√2 ↦ -√2, √3 ↦ -√3`), they agree on `F`, and the relation
  on `α` propagates by multiplicativity to give
      `σ τ σ⁻¹ = τ⁻¹`,   equivalently `τ σ = σ⁻¹ τ`.
  Combined with `σ⁴ = 1`, `τ² = σ²`, this is the quaternion
  presentation
      `Q₈ = ⟨a, x ∣ a⁴ = 1, x² = a², x a x⁻¹ = a⁻¹⟩`.

Step 6 — Identification with `QuaternionGroup 2`.
  `Mathlib.GroupTheory.SpecificGroups.Quaternion` defines
      `QuaternionGroup n := { a : ZMod (2n) } ⊕ { xa : ZMod (2n) }`
  with `n = 2` giving the quaternion group `Q₈` of order `4·2 = 8`,
  generated by `a := ⟨1⟩` of order `4` and `x := ⟨0⟩_{xa}` with the
  exact relations `a⁴ = 1`, `x² = a²`, `x·a·x⁻¹ = a⁻¹`.
  Sending the generator `a ↦ σ` and `x ↦ τ` and extending
  multiplicatively gives a group isomorphism
      `QuaternionGroup 2 ≃* (E ≃ₐ[ℚ] E)`.
  Inverting this yields `(E ≃ₐ[ℚ] E) ≃* QuaternionGroup 2`, and the
  goal `Nonempty …` is satisfied.

Mathlib status.  Each individual step (degree calculations via
`Algebra.adjoin`, irrationality of `√2, √3, √6`, the explicit
construction of automorphisms, and the verification of `Q₈`-relations
against `Mathlib`'s `QuaternionGroup 2`) admits a routine but
nontrivial formalisation.  Mathlib has no infrastructure linking
specific number-field Galois groups to `QuaternionGroup`, so the
construction must be performed by hand: producing eight automorphisms
of `E`, exhibiting them as a `MulEquiv` to `QuaternionGroup 2`, and
checking the multiplication table.  We record the theorem with a
single `sorry` while the roadmap above carries the full argument.
-/

/--
Let $\alpha = \sqrt{(2+\sqrt 2)(3+\sqrt 3)}$ and consider the extension $E =\mathbb{Q}(\alpha)$.
Show that $\mathrm{Gal}(E/\mathbb{Q}) \cong Q_8$, the quaternion group of order $8$.
-/
theorem galoisGroup_iso_quaternion_group : Nonempty ((E ≃ₐ[ℚ] E) ≃* (QuaternionGroup 2)) := by
  sorry

end Problem19
