import Mathlib

namespace Problem20

open IntermediateField

/--
Let $p$ be a prime number. Let $L/K$ be a finite extension of fields of characteristic $p$,
and let $\sigma:x\mapsto x^p$ denote the $p$-Frobenius endomorphism on $L$, which of course
stabilizes $K$. Prove that if $[L:K\sigma(L)] \leq p$, then $L/K$ can be generated by one element.
-/
theorem generated_single_elem_of_degree_le_p (p : ℕ) [Fact (Nat.Prime p)]
    (K L : Type) [Field K] [Field L] [CharP L p] [Algebra K L] [FiniteDimensional K L]
    (h : Module.rank (IntermediateField.adjoin K ((frobenius L p).range : Set L)) L ≤ p) :
    ∃ (x : L), IntermediateField.adjoin K {x} = ⊤ := by
  -- Set M = K(L^p) = K · σ(L); this is the IntermediateField from the hypothesis.
  set M : IntermediateField K L := IntermediateField.adjoin K ((frobenius L p).range : Set L)
    with hM_def
  -- Inherit characteristic instances.
  haveI : CharP M p := IntermediateField.charP' M p
  haveI : ExpChar M p := expChar_prime M p
  -- Key: L/M is purely inseparable: for any x ∈ L, x^p = frobenius L p x ∈ frobenius.range ⊆ M.
  have hpurely : IsPurelyInseparable M L := by
    rw [isPurelyInseparable_iff_pow_mem _ p]
    intro x
    refine ⟨1, ?_⟩
    rw [pow_one]
    refine ⟨⟨frobenius L p x, ?_⟩, rfl⟩
    apply IntermediateField.subset_adjoin
    exact ⟨x, rfl⟩
  -- Convert rank ≤ ↑p to finrank ≤ p.
  have hfinrank_le : Module.finrank M L ≤ p := Module.finrank_le_of_rank_le h
  -- Since L/M is purely inseparable, [L:M] is a power of p.
  obtain ⟨n, hn⟩ : ∃ n, Module.finrank M L = p ^ n :=
    IsPurelyInseparable.finrank_eq_pow M L p
  have hp_prime : p.Prime := Fact.out
  have hp1 : 1 < p := hp_prime.one_lt
  -- Combined with [L:M] ≤ p and p ≥ 2, this forces n ≤ 1, hence [L:M] ∈ {1, p}.
  have hn_le_one : n ≤ 1 := by
    by_contra hn_gt
    push_neg at hn_gt
    have h2n : p ^ 2 ≤ p ^ n := Nat.pow_le_pow_right hp1.le hn_gt
    rw [← hn] at h2n
    have hp2 : p ^ 2 ≤ p := h2n.trans hfinrank_le
    nlinarith [sq_nonneg (p - 1), hp_prime.two_le]
  interval_cases n
  · -- Case [L:M] = 1: then M = ⊤, so L = K(L^p).
    -- This implies L/K is separable, and the standard primitive element theorem applies.
    rw [pow_zero] at hn
    have hMtop : M = ⊤ := IntermediateField.finrank_eq_one_iff_eq_top.mp hn
    -- Claim: L/K is separable when L = K(L^p).
    -- Standard fact: in characteristic p, a finite extension L/K is separable iff L = K(L^p).
    -- The classical proof uses a basis argument: pick a K-basis e_1,…,e_n of L. Since L = K(L^p),
    -- the family {e_i^p} also K-spans L, hence is a K-basis (matching cardinality in finite dim).
    -- This implies the trace form is non-degenerate, hence L/K is separable.
    -- Mathlib has the *converse* (`Field.span_map_pow_expChar_pow_eq_top_of_isSeparable`,
    -- `LinearIndependent.map_pow_expChar_pow_of_isSeparable`) but **not** the forward direction
    -- (K(L^p) = L ⟹ Algebra.IsSeparable K L) as a directly-usable lemma in Mathlib v4.28.0.
    -- Tower-degree formulas (`Field.finInsepDegree_mul_finInsepDegree_of_isAlgebraic`,
    -- `Field.rank_mul_insepDegree_of_isPurelyInseparable`) all turn out to be tautological when
    -- M = ⊤ (since then M ≃ₐ[K] L), so they don't help. Constructing the basis-based proof from
    -- scratch is substantial work (~50–100 lines) and is left as a focused sorry here.
    have hSep : Algebra.IsSeparable K L := by
      -- Inherit char-p instance to K
      haveI : CharP K p := by
        constructor
        intro n
        rw [← (algebraMap K L).injective.eq_iff, map_natCast, map_zero]
        exact CharP.cast_eq_zero_iff L p n
      haveI : ExpChar K p := ExpChar.prime Fact.out
      -- Step 1: K-span of (frobenius L p).range = ⊤ (since the IntermediateField adjoin = ⊤,
      -- and the range is multiplicatively closed, so adjoin = K-span).
      have h_span_Lp : Submodule.span K ((frobenius L p).range : Set L) = ⊤ := by
        haveI : Algebra.IsAlgebraic K L := Algebra.IsAlgebraic.of_finite K L
        have hAlg : ∀ x ∈ ((frobenius L p).range : Set L), IsAlgebraic K x :=
          fun x _ ↦ Algebra.IsAlgebraic.isAlgebraic x
        have hCl : Submonoid.closure ((frobenius L p).range : Set L) =
                   (frobenius L p).range.toSubmonoid := Submonoid.closure_eq _
        have h2 := Algebra.adjoin_eq_span K ((frobenius L p).range : Set L)
        rw [hCl] at h2
        have h1 : (IntermediateField.adjoin K ((frobenius L p).range : Set L)).toSubalgebra =
                  Algebra.adjoin K ((frobenius L p).range : Set L) :=
          IntermediateField.adjoin_toSubalgebra_of_isAlgebraic hAlg
        rw [← hM_def, hMtop, IntermediateField.top_toSubalgebra] at h1
        rw [← h1, Algebra.top_toSubmodule] at h2
        exact h2.symm
      -- Step 2: For any K-basis b of L, the family (b · ^ p) also K-spans L.
      -- Reason: K-span (b·^p) ⊇ {b_j^p} ⊆ frob.range (so ⊆ direction by membership).
      -- Conversely, every element of frob.range is x^p for some x = Σ a_i b_i, and Frobenius
      -- gives x^p = Σ a_i^p b_i^p with a_i^p ∈ K, hence in K-span (b·^p).
      have h_basis_p_span : ∀ {ι : Type} (b : Module.Basis ι K L),
                            Submodule.span K (Set.range (fun i ↦ b i ^ p)) = ⊤ := by
        intro ι b
        rw [← h_span_Lp]
        apply le_antisymm
        · exact Submodule.span_le.mpr
            (by rintro _ ⟨i, rfl⟩; exact Submodule.subset_span ⟨b i, rfl⟩)
        · apply Submodule.span_le.mpr
          rintro y ⟨x, rfl⟩
          have hx : x ∈ Submodule.span K (Set.range b) := by rw [b.span_eq]; trivial
          refine Submodule.span_induction ?_ ?_ ?_ ?_ hx
          · rintro _ ⟨j, rfl⟩
            simp only [SetLike.mem_coe, frobenius_def]
            exact Submodule.subset_span ⟨j, by simp⟩
          · show frobenius L p 0 ∈ _; rw [map_zero]; exact Submodule.zero_mem _
          · intro x y _ _ hxs hys
            show frobenius L p (x + y) ∈ _; rw [map_add]
            exact Submodule.add_mem _ hxs hys
          · intro a x _ hxs
            show frobenius L p (a • x) ∈ _
            rw [Algebra.smul_def, map_mul]
            have : frobenius L p (algebraMap K L a) = algebraMap K L (a^p) := by
              rw [frobenius_def, ← map_pow]
            rw [this, ← Algebra.smul_def]
            exact Submodule.smul_mem _ _ hxs
      -- Step 3: From step 2, deduce that for any K-LinIndep family s ⊆ L, (· ^ p) '' s is also
      -- K-LinIndep — by extending s to a basis B, observing B^p is again a K-basis (LinIndep
      -- via dimension count), and noting s^p ⊆ B^p is a subfamily of a LinIndep family.
      have H : ∀ s : Finset L, LinearIndepOn K _root_.id (s : Set L) →
                        LinearIndepOn K (fun x ↦ x ^ p) (s : Set L) := by
        intro s hs
        classical
        let s' : Set L := hs.extend (Set.subset_univ _)
        have hs_sub_s' : (s : Set L) ⊆ s' := LinearIndepOn.subset_extend hs (Set.subset_univ _)
        let b : Module.Basis ↑s' K L := Module.Basis.extend hs
        have hb_id : ∀ (x : ↑s'), b x = x.val := Module.Basis.extend_apply_self hs
        haveI : Finite ↑s' := Module.Finite.finite_basis b
        haveI : Fintype ↑s' := Fintype.ofFinite _
        have h_li_s' : LinearIndependent K (fun x : ↑s' ↦ x.val ^ p) := by
          have h0 : LinearIndependent K (fun x : ↑s' ↦ b x ^ p) := by
            apply linearIndependent_of_top_le_span_of_card_eq_finrank
            · rw [h_basis_p_span b]
            · rw [Module.finrank_eq_card_basis b]
          convert h0 using 1
          funext x; rw [hb_id]
        let emb : ↑(s : Set L) → ↑s' := fun x ↦ ⟨x.val, hs_sub_s' x.2⟩
        have emb_inj : Function.Injective emb := fun x y h ↦
          Subtype.ext (Subtype.mk.injEq _ _ _ _ |>.mp h)
        exact h_li_s'.comp emb emb_inj
      -- Step 4: Apply the Mathlib lemma to get a separable transcendence basis, which since
      -- L/K is finite (algebraic) must be empty, hence L is separable over adjoin K ∅ = ⊥ ≃ K.
      have hp_prime : p.Prime := Fact.out
      obtain ⟨s, hs_tb, hs_sep⟩ :=
        exists_isTranscendenceBasis_and_isSeparable_of_linearIndepOn_pow_of_essFiniteType
          p hp_prime H
      haveI : Algebra.IsAlgebraic K L := Algebra.IsAlgebraic.of_finite K L
      have h_empty : IsEmpty ↑(s : Set L) := hs_tb.1.isEmpty_of_isAlgebraic
      have hs_emp : (s : Set L) = ∅ := by
        ext x
        refine ⟨fun hx ↦ h_empty.elim ⟨x, hx⟩, fun h ↦ h.elim⟩
      rw [hs_emp, IntermediateField.adjoin_empty] at hs_sep
      haveI := hs_sep
      haveI : Algebra.IsSeparable K (⊥ : IntermediateField K L) := inferInstance
      exact Algebra.IsSeparable.trans K (⊥ : IntermediateField K L) L
    obtain ⟨α, hα⟩ := Field.exists_primitive_element K L
    exact ⟨α, hα⟩
  · -- Case [L:M] = p: this is the deeper case (Becker–MacLane theorem in characteristic p).
    -- Here L/M is purely inseparable of degree exactly p, and we need to construct a primitive
    -- element of L over K. The classical Becker–MacLane proof picks α ∈ L \ M (which exists
    -- since [L:M] = p > 1) and shows K⟮α⟯ = L via a careful intermediate-field analysis: one
    -- shows [K⟮α⟯ : K⟮α⟯ ∩ M] = p (using L = M(α) since [L:M] = p with L/M purely inseparable),
    -- and then leverages that M = K(L^p) to force K⟮α⟯ ∩ M = M, hence K⟮α⟯ ⊇ M, hence
    -- K⟮α⟯ ⊇ M(α) = L. The last forcing step uses an inductive argument on [M:K] together with
    -- a non-trivial choice of α (typically α + β for an existing primitive element β of M/K).
    -- This argument is substantial (~80–150 lines) and not currently formalized in Mathlib.
    rw [pow_one] at hn
    -- Step A: M ≠ ⊤ (since [L:M] = p > 1).
    have hM_ne_top : M ≠ ⊤ := by
      intro hMt
      rw [IntermediateField.finrank_eq_one_iff_eq_top.mpr hMt] at hn
      exact (Nat.lt_irrefl 1) (hn ▸ hp1)
    -- Step B: Pick α ∈ L \ M.
    have hM_lt_top : M < ⊤ := lt_of_le_of_ne le_top hM_ne_top
    obtain ⟨α, _, hα_not⟩ : ∃ α ∈ (⊤ : IntermediateField K L), α ∉ M :=
      SetLike.exists_of_lt hM_lt_top
    -- Step C: M⟮α⟯ = ⊤ as an IntermediateField over M (since L/M is purely inseparable of
    -- degree p and α ∉ M, so [M⟮α⟯ : M] > 1, but [M⟮α⟯ : M] divides [L:M] = p, hence equals p).
    -- Equivalently, IntermediateField.adjoin M ({α} : Set L) = ⊤.
    -- Build the primitive element step-by-step. The key remaining gap is to establish
    -- K⟮γ⟯ = ⊤ for some γ, which requires the full Becker–MacLane argument.
    --
    -- Mathematical obstruction: We need a Mathlib lemma of roughly the form
    --   "if [L:M] = p, M = K(L^p), L/M purely inseparable, then ∃ γ, K⟮γ⟯ = L"
    -- This corresponds to Becker–MacLane (1940) and is not currently in Mathlib.
    -- The argument uses an inductive choice of γ = α + β for a primitive element β of
    -- separableClosure K L over K, together with a delicate degree-counting argument.
    sorry

end Problem20
