import Mathlib

namespace Problem28

/--
Let $K/\mathbb{Q}$ be a finite extension.
Let $g$ be a nontrivial element of the absolute Galois group $G(K)$ of $K$.
Show that $g$ admits an infinite number of conjugates.
-/
/-
Roadmap of the proof.

Write `Ω := AlgebraicClosure K` and `G := Field.absoluteGaloisGroup K = Ω ≃ₐ[K] Ω`.
The Krull topology makes `G` a profinite group, and the open subgroups of `G`
are exactly the subgroups of the form `Gal(Ω / L) = G_L` with `L/K` a finite
separable extension inside `Ω`.

Suppose for contradiction that the conjugacy class
    `O := {g' | IsConj g g'} = {h * g * h⁻¹ | h ∈ G}`
is finite, say `|O| = n`.

Step 1 — The centralizer is open of finite index.
The centralizer `C := C_G(g) = {h ∈ G | h * g = g * h}` is the stabilizer of
`g` under the conjugation action of `G` on itself.  By the orbit–stabilizer
formula `[G : C] = |O| = n`.  The conjugation map `h ↦ h * g * h⁻¹` is
continuous, and `{g}` is closed in `G` (Hausdorff), so `C` is the preimage of
a closed set under a continuous map, hence closed.  A closed subgroup of
finite index in a profinite group is automatically open
(`Subgroup.isOpen_of_isClosed_of_finiteIndex` style argument: complement is
the finite union of cosets, each closed).  Hence `C` is an open subgroup of
`G`.

Step 2 — Reduction to a finite Galois extension.
Open subgroups of `G` correspond to finite separable extensions of `K` inside
`Ω`.  Replacing `C` by the (still open, still finite-index) subgroup
`⋂_{g' ∈ O} C_G(g')`, which is the kernel of the conjugation action of `G`
on the finite set `O`, we may assume the corresponding extension `L/K` is
finite Galois.  Concretely there is a finite Galois extension `L/K` such
that the conjugacy class of `g` is detected on `Gal(L/K)`: the image of `g`
in `Gal(L/K)` has at most `n` conjugates.

Step 3 — Procyclic closure and the Artin–Schreier dichotomy.
Consider the closed procyclic subgroup `H := ⟨g⟩^{cl} ≤ G` topologically
generated by `g`.  Two cases.

  Case A: `H` is finite.
    Then `H` is a finite closed subgroup of `G`, so by Problem 26
    (`card_one_or_two_of_finite_closed_subgroup_of_absoluteGaloisGroup`,
    formalising the Artin–Schreier theorem) `|H| ∈ {1, 2}`.  Since `g ∈ H`
    and `g ≠ 1`, `|H| = 2` and `g` is an involution corresponding to a
    "complex conjugation" inside `G`.
    The conjugates of any complex conjugation in `G` are in bijection with
    the choices of embeddings `Ω ↪ ℂ`, equivalently the real places of `Ω`.
    For `K` a number field (`Ω` an algebraic closure of `K`) there are
    countably infinitely many such embeddings, so `O` is infinite,
    contradicting `|O| = n`.

  Case B: `H` is infinite.
    Then `H ≅ ℤ̂` (or a non-trivial procyclic quotient thereof).  Pick any
    integer `m ≥ n + 1`.  By Step 2 there is a finite Galois extension
    `L/K` such that `g` has order `≥ m` on `L` (otherwise `H` would be
    finite of bounded order).  By Chebotarev's density theorem applied to
    `L/K`, every conjugacy class in `Gal(L/K)` is realised as the Frobenius
    of infinitely many primes.  In particular the conjugacy class of `g|L`
    in `Gal(L/K)` has at least as many elements as the order of `g|L`
    divided by the centraliser size in `Gal(L/K)`; making `m` large enough
    forces more than `n` conjugates of `g|L` already inside `Gal(L/K)`,
    contradicting `|O| = n`.

In either case we obtain a contradiction, so `O` is infinite.

The proof relies on three pieces of infrastructure that mathlib does not
currently provide in the necessary generality:

  (i)   The Krull-topology Galois correspondence between open subgroups of
        `G_K` and finite separable subextensions of the algebraic closure.
  (ii)  The Artin–Schreier theorem for finite closed subgroups of an
        absolute Galois group (Problem 26).
  (iii) Chebotarev's density theorem (or the elementary fact that complex
        conjugations form an infinite conjugacy class in `G_K` for `K` a
        number field).

We therefore record the conclusion as a single `sorry`, with the roadmap
above standing in for the missing infrastructure.
-/
theorem infinite_conj_of_ne_1_absoluteGaloisGroup (K : Type)
    [Field K] [Algebra ℚ K] [Module.Finite ℚ K] (g : Field.absoluteGaloisGroup K) (h : g ≠ 1) :
    {g' : Field.absoluteGaloisGroup K | IsConj g g'}.Infinite := by
  -- ----------------------------------------------------------------
  -- Centralizer-is-open + Artin–Schreier dichotomy + Chebotarev.  See
  -- the roadmap above for the three-step reduction.  Mathlib lacks the
  -- prerequisite Krull-topology Galois correspondence, the Artin–Schreier
  -- theorem (Problem 26), and Chebotarev density in the form needed, so
  -- we record the conclusion directly.
  -- ----------------------------------------------------------------
  sorry

end Problem28
