import Mathlib

namespace Problem29

/--
Let $K/\mathbb{Q}$ be a finite extension. Let $g$ be an element of the absolute Galois group
$G(K)$ of $K$. Show that the subgroup generated by $g$ is closed in $G(K)$ if and only if $g$
is torsion.
-/
/-
Roadmap of the proof.

Write `Ω := AlgebraicClosure K` and `G := Field.absoluteGaloisGroup K = Ω ≃ₐ[K] Ω`.
With the Krull topology `G` is a profinite (in particular Hausdorff and compact)
topological group.

(⇐) Easy direction: if `g` is torsion, then `Subgroup.zpowers g = ⟨g⟩` is finite,
and any finite set in a `T1` space is closed.

(⇒) Hard direction: assume `H := Subgroup.zpowers g` is closed in `G`. Then `H`
is a closed subgroup of a compact Hausdorff topological group, so the subspace
`H` is itself a compact Hausdorff topological group. The set `↑H` is the image
of `ℤ` under `n ↦ g ^ n`, hence countable. Now suppose for contradiction that
`↑H` is infinite. Then `H` is a nonempty compact Hausdorff Baire space, covered
by countably many singletons `{⟨g ^ n, _⟩}`. The Baire category theorem yields a
point `x₀ ∈ H` whose singleton has nonempty interior; translating by `x₀⁻¹`
makes `{1}` open, so `H` carries the discrete topology. A compact discrete
space is finite, contradicting infinitude. Thus `H` is finite and
`finite_zpowers` gives `IsOfFinOrder g`.
-/
theorem isClosed_zpowers_iff_isOfFinOrder (K : Type)
    [Field K] [Algebra ℚ K] [Module.Finite ℚ K] (g : Field.absoluteGaloisGroup K) :
    IsClosed ((Subgroup.zpowers g) : Set (Field.absoluteGaloisGroup K)) ↔ IsOfFinOrder g := by
  have hT2 : T2Space (Field.absoluteGaloisGroup K) := by
    unfold Field.absoluteGaloisGroup
    haveI : Algebra.IsIntegral K (AlgebraicClosure K) := Algebra.IsAlgebraic.isIntegral
    exact krullTopology_t2
  haveI : CharZero K := charZero_of_injective_algebraMap (algebraMap ℚ K).injective
  haveI : IsGalois K (AlgebraicClosure K) := IsAlgClosure.isGalois K _
  haveI : CompactSpace (Field.absoluteGaloisGroup K) := by
    unfold Field.absoluteGaloisGroup; infer_instance
  haveI : IsTopologicalGroup (Field.absoluteGaloisGroup K) := by
    unfold Field.absoluteGaloisGroup; infer_instance
  refine ⟨?_, ?_⟩
  · -- Forward direction: closed ⟨g⟩ ⇒ `g` has finite order.
    intro hH
    rw [← finite_zpowers]
    by_contra hinf
    rw [Set.not_finite] at hinf
    set Hsub : Subgroup (Field.absoluteGaloisGroup K) := Subgroup.zpowers g
    haveI : CompactSpace Hsub := isCompact_iff_compactSpace.mp hH.isCompact
    haveI : WeaklyLocallyCompactSpace Hsub :=
      ⟨fun _ => ⟨Set.univ, isCompact_univ, Filter.univ_mem⟩⟩
    haveI : BaireSpace Hsub := BaireSpace.of_t2Space_locallyCompactSpace
    have hHrange : (↑Hsub : Set (Field.absoluteGaloisGroup K)) =
        Set.range (fun n : ℤ => g ^ n) := by
      ext x; simp [Hsub, Subgroup.mem_zpowers_iff]
    have hCntS : (↑Hsub : Set (Field.absoluteGaloisGroup K)).Countable :=
      hHrange ▸ Set.countable_range _
    haveI : Countable Hsub := hCntS.to_subtype
    haveI : Nonempty Hsub := ⟨1⟩
    have hcover : (⋃ x : Hsub, ({x} : Set Hsub)) = Set.univ := Set.iUnion_of_singleton _
    obtain ⟨x₀, hx₀⟩ : ∃ x : Hsub, (interior ({x} : Set Hsub)).Nonempty :=
      nonempty_interior_of_iUnion_of_closed (fun _ => isClosed_singleton) hcover
    have h1 : IsOpen ({x₀} : Set Hsub) := by
      obtain ⟨y, hy⟩ := hx₀
      rw [mem_interior] at hy
      obtain ⟨U, hU₁, hU₂, hU₃⟩ := hy
      have hyx : y = x₀ := hU₁ hU₃
      have hUeq : U = {x₀} := Set.eq_singleton_iff_unique_mem.mpr
        ⟨hyx ▸ hU₃, fun z hz => hU₁ hz⟩
      rwa [← hUeq]
    haveI : DiscreteTopology Hsub := by
      rw [discreteTopology_iff_isOpen_singleton_one]
      have heq : ({1} : Set Hsub) = Homeomorph.mulLeft x₀⁻¹ '' {x₀} := by simp
      rw [heq]
      exact (Homeomorph.mulLeft x₀⁻¹).isOpen_image.mpr h1
    haveI : Finite Hsub := finite_of_compact_of_discrete
    exact hinf (Set.toFinite _)
  · -- Backward direction: `g` of finite order ⇒ ⟨g⟩ is finite ⇒ ⟨g⟩ is closed.
    intro hg
    exact hg.finite_zpowers.isClosed

end Problem29
