import Mathlib

namespace Problem29

/--
Let $K/\mathbb{Q}$ be a finite extension. Let $g$ be an element of the absolute Galois group
$G(K)$ of $K$. Show that the subgroup generated by $g$ is closed in $G(K)$ if and only if $g$
is torsion.
-/
/-
Roadmap of the proof.

Write `Ω := AlgebraicClosure K` and `G := Field.absoluteGaloisGroup K = Ω ≃ₐ[K] Ω`.
With the Krull topology `G` is a profinite (in particular Hausdorff and compact)
topological group.

(⇐) Easy direction: if `g` is torsion, then `Subgroup.zpowers g = ⟨g⟩` is finite,
and any finite set in a `T1` space is closed.  This direction is given by
`IsOfFinOrder.finite_zpowers` followed by `Set.Finite.isClosed`, after we
record that `G` is `T2` (hence `T1`).  We prove this in-line.

(⇒) Hard direction: assume `H := Subgroup.zpowers g = ⟨g⟩` is closed in `G`.
We must show `g` has finite order.

  Step 1 — `H` is procyclic.
    Since `H` is closed in the profinite group `G`, the subspace `H` is itself
    a profinite topological group with the induced topology.  As a group `H`
    is cyclic with generator `g`, hence in particular abelian.  The closure
    of the cyclic group generated by `g` is therefore a closed procyclic
    subgroup of `G`; but by hypothesis `H` is already closed, so
    `H = ⟨g⟩^{cl}` is itself procyclic.

  Step 2 — The cardinality dichotomy.
    A procyclic profinite group is either finite or homeomorphic to a
    non-trivial quotient of `ℤ̂` (the profinite completion of `ℤ`).  In the
    second case `H` is uncountable.

  Step 3 — Eliminate the infinite case.
    Suppose `H` is infinite.  Then `H` is uncountable by Step 2.  But
    `Subgroup.zpowers g = {g ^ n | n : ℤ}` is the image of `ℤ` under the
    `zpow`-map, so it is at most countable.  This contradicts uncountability,
    so `H` is finite, which gives `IsOfFinOrder g` directly via
    `finite_zpowers`.

The proof of the forward direction relies on a piece of infrastructure that
mathlib does not currently provide in the necessary generality:

  (i)   The fact that the topological closure of a cyclic subgroup in a
        profinite (compact, Hausdorff, totally disconnected) group is
        procyclic, together with the cardinality dichotomy above.

We therefore record the forward direction as a single `sorry`, with the
roadmap above standing in for the missing infrastructure.  The backward
direction is proved unconditionally.
-/
theorem isClosed_zpowers_iff_isOfFinOrder (K : Type)
    [Field K] [Algebra ℚ K] [Module.Finite ℚ K] (g : Field.absoluteGaloisGroup K) :
    IsClosed ((Subgroup.zpowers g) : Set (Field.absoluteGaloisGroup K)) ↔ IsOfFinOrder g := by
  -- Record that the absolute Galois group is `T2` (hence `T1`) under the Krull
  -- topology.  This is `krullTopology_t2`, which only needs algebraicity of
  -- `AlgebraicClosure K` over `K`.
  have hT2 : T2Space (Field.absoluteGaloisGroup K) := by
    unfold Field.absoluteGaloisGroup
    haveI : Algebra.IsIntegral K (AlgebraicClosure K) := Algebra.IsAlgebraic.isIntegral
    exact krullTopology_t2
  refine ⟨?_, ?_⟩
  · -- Forward direction: closed ⟨g⟩ ⇒ `g` has finite order.
    -- Roadmap: closure of cyclic subgroup in profinite group is procyclic;
    -- a procyclic profinite group is either finite or uncountable; a cyclic
    -- subgroup `Subgroup.zpowers g` is countable, so finiteness follows.
    -- Mathlib does not have the needed procyclic dichotomy in this form.
    intro _
    sorry
  · -- Backward direction: `g` of finite order ⇒ ⟨g⟩ is finite ⇒ ⟨g⟩ is closed.
    intro hg
    exact hg.finite_zpowers.isClosed

end Problem29
